id: P000358
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23624
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་བླ་མ་རིག་འཛིན་འདུས་པའི་གདང་རོལ་ཉུང་ངུ་བློ་གསལ་མགུལ་རྒྱན་གཏོར་མའི་དཔེའུ་རིས་བཅས་དང་པད་གླིང་གི་དབྱངས་ཡིག
  author: ''
  volumes:
    066f977a32434be5836878c2009f980e:
      image_group_id: I3200
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
